### ISSUE TITLE
Crash when using miner

### ISSUE THREAD

**Issue by Mewtwoy** [GabrielOlvH/Industrial-Revolution#17]
Description: Ticking block entity

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at me.steven.indrev.utils.UtilsKt.getChunkPos(UtilsKt.java:78)
	at me.steven.indrev.blockentities.farms.MinerBlockEntity.machineTick(MinerBlockEntity.java:68)
	at me.steven.indrev.blockentities.MachineBlockEntity.method_16896(MachineBlockEntity.java:77)
	at net.minecraft.class_1937.method_18471(class_1937.java:552)
	at net.minecraft.class_3218.method_18765(class_3218.java:423)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$5094/516821284.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by GabrielOlvH** [comment]
That seems odd... The Scan Output you placed on the machine did not have the chunk data. How did you get that scan?

**Comment by GabrielOlvH** [comment]
As of 1.3.0-BETA this crash shouldn't happen anymore, but the miner doesn't work without the Scan Output corresponding to it's location. To get that, use the Chunk Scanner. Let me know if you have any other issues.

**Comment by GabrielOlvH** [comment]
As of 1.3.0-BETA this does not happen anymore, however you need the corresponding Scan Output to the miner's location. You can get that by using the Chunk Scanner. Let me know if you have any other issues
