### ISSUE TITLE
[BUG] Tank error 1.17.1

### ISSUE THREAD

**Issue by red2blue** [GabrielOlvH/Industrial-Revolution#314]
Latest version of indrev
mc 1.17.1

Player had this in their logs who joined my dedicated server for AQM2

[12:28:39] [Render thread/WARN]: [config] Failed to write the config file!
java.nio.file.NoSuchFileException: C:\Users\noctu\curseforge\minecraft\Instances\Another Quality Modpack 2\libblockattributes_fluids.txt
    at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
    at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
    at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]
    at java.nio.file.Files.newOutputStream(Files.java:224) ~[?:?]
    at java.nio.file.Files.newBufferedWriter(Files.java:2997) ~[?:?]
    at alexiil.mc.lib.attributes.fluid.LbaFluidsConfig.<clinit>(LbaFluidsConfig.java:95) ~[4dd95716-6178-4893-9658-ec19b0a8efd8.jar:?]
    at alexiil.mc.lib.attributes.fluid.volume.FluidTooltipContext.shouldStripFluidColours(FluidTooltipContext.java:81) ~[4dd95716-6178-4893-9658-ec19b0a8efd8.jar:?]
    at alexiil.mc.lib.attributes.fluid.volume.FluidTooltipContext.stripFluidColours(FluidTooltipContext.java:192) ~[4dd95716-6178-4893-9658-ec19b0a8efd8.jar:?]
    at alexiil.mc.lib.attributes.fluid.volume.FluidKey.addFullTooltip(FluidKey.java:872) ~[4dd95716-6178-4893-9658-ec19b0a8efd8.jar:?]
    at alexiil.mc.lib.attributes.fluid.volume.FluidKey.getFullTooltip(FluidKey.java:866) ~[4dd95716-6178-4893-9658-ec19b0a8efd8.jar:?]
    at alexiil.mc.lib.attributes.fluid.volume.FluidKey.getFullTooltip(FluidKey.java:856) ~[4dd95716-6178-4893-9658-ec19b0a8efd8.jar:?]
    at me.steven.indrev.blocks.misc.TankBlock.appendTooltip(TankBlock.java:182) ~[indrev-1.10.0-alpha.12.jar:?]
    at net.minecraft.item.BlockItem.appendTooltip(BlockItem:209) ~[?:?]
    at net.minecraft.item.ItemStack.getTooltip(ItemStack:677) ~[?:?]
    at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen:181) ~[?:?]
    at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen:168) ~[?:?]
    at net.minecraft.client.gui.screen.ingame.HandledScreen.drawMouseoverTooltip(HandledScreen:190) ~[?:?]
    at net.minecraft.client.gui.screen.ingame.GenericContainerScreen.render(GenericContainerScreen:32) ~[?:?]
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:874) ~[?:?]
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
    at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]

**Comment by GabrielOlvH** [comment]
Thanks for reporting, but you can safely ignore this, it doesn't affect anything and it won't happen anymore after the next update. I'll be closing this just to keep the issue tracker clean for more important issues.
