### ISSUE TITLE
[BUG] slaughter_mk1 crashed the server with Ticking block entity

### ISSUE THREAD

**Issue by ColdTearsYY** [GabrielOlvH/Industrial-Revolution#491]
**Description:**
- slaughter_mk1 crashed the server

**Steps to Reproduce:**
- put a slaughter_mk1 and the server crashed

**Technical Information:**
 - Minecraft: 1.19.2
 - Fabric API: Fabric API 0.62.0+1.19.2
 - Industrial Revolution: Industrial Revolution 1.15.0-BETA  fake-player-api: Fake Player API 0.4.0
 - Modpack: none

**Logs:**
- crash-report:https://paste.ubuntu.com/p/B47XnXzqtF/
- latest.log:https://paste.ubuntu.com/p/Mw8g3FqjPB/

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by ghost** [comment]
same error still occurs in 1.15.1-BETA

**Comment by RubberDuckyDJ** [comment]
this issue still happens on 1.15.2-BETA-fab15hotfix2

Neurina Crash:

java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at knot//net.minecraft.class_3244.handler$zif000$adventure-platform-fabric$adventure$initTracking(class_3244.java:3544)
	at knot//net.minecraft.class_3244.<init>(class_3244.java:242)
	at knot//dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)
	at knot//dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:20)
	at knot//me.steven.indrev.IndustrialRevolution$FAKE_PLAYER_BUILDER$1$1.<init>(IndustrialRevolution.kt:153)
	at knot//me.steven.indrev.IndustrialRevolution.FAKE_PLAYER_BUILDER$lambda-10(IndustrialRevolution.kt:153)
	at knot//dev.cafeteria.fakeplayerapi.server.FakePlayerBuilder.create(FakePlayerBuilder.java:38)
	at knot//me.steven.indrev.blockentities.farms.SlaughterBlockEntity$fakePlayer$2.invoke(SlaughterBlockEntity.kt:40)
	at knot//me.steven.indrev.blockentities.farms.SlaughterBlockEntity$fakePlayer$2.invoke(SlaughterBlockEntity.kt:40)
	at knot//kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
	at knot//me.steven.indrev.blockentities.farms.SlaughterBlockEntity.getFakePlayer(SlaughterBlockEntity.kt:40)
	at knot//me.steven.indrev.blockentities.farms.SlaughterBlockEntity.machineTick(SlaughterBlockEntity.kt:48)
	at knot//me.steven.indrev.blockentities.MachineBlockEntity.tick(MachineBlockEntity.kt:96)
	at knot//me.steven.indrev.blocks.machine.MachineBlock.getTicker$lambda-1(MachineBlock.kt:71)
	at knot//net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(class_2818.java)
	at knot//com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169)
	at knot//net.minecraft.class_2818$class_5563.wrapOperation$fnh000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(class_2818.java:1285)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at knot//net.minecraft.class_1937.redirect$foe000$observable$redirectTick(class_1937.java:14567)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:456)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:376)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:289)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)
