### ISSUE TITLE
[BUG] Using modular workbench crashes the server

### ISSUE THREAD

**Issue by Fishent123** [GabrielOlvH/Industrial-Revolution#593]
**Description:**
right clicking the modular workbench on a server crashes it

**Steps to Reproduce:**
- right clicking the modular workbench

**Technical Information:**
 - Minecraft: 1.19.2
 - Fabric API: 0.77.0
 - Industrial Revolution: v1.15.2-BETA-fab15hotfix
 - Modpack: Tekxit4

**Logs:**
- java.lang.NoClassDefFoundError: net/minecraft/class_1113
	at me.steven.indrev.WCustomTabPanel.add(WCustomTabPanel.java:96)
	at me.steven.indrev.WCustomTabPanel.add(WCustomTabPanel.java:116)
	at me.steven.indrev.gui.screenhandlers.machines.ModularWorkbenchScreenHandler.<init>(ModularWorkbenchScreenHandler.kt:116)
	at me.steven.indrev.registry.MachineRegistry$Companion$MODULAR_WORKBENCH_REGISTRY$1$1.invoke(MachineRegistry.kt:637)
	at me.steven.indrev.registry.MachineRegistry$Companion$MODULAR_WORKBENCH_REGISTRY$1$1.invoke(MachineRegistry.kt:637)
	at me.steven.indrev.gui.IRScreenHandlerFactory.createMenu(IRScreenHandlerFactory.kt:19)
	at net.minecraft.class_3222.method_17355(class_3222.java:1040)
	at me.steven.indrev.blocks.machine.MachineBlock.method_9534(MachineBlock.kt:103)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1113
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 27 more

**Details:**
- My server is running with 6gb ram

**Comment by SlayerTheChikken** [comment]
It is good to post crash reports but in this case you have reported a bug for a fork I made :p

**Comment by SlayerTheChikken** [comment]
https://github.com/GabrielOlvH/Industrial-Revolution/pull/586
