### ISSUE TITLE
Latest version crashes on MC 1.16.1 Fabric 0.6.1.45 server

### ISSUE THREAD

**Issue by grapereader** [GabrielOlvH/Industrial-Revolution#7]
Crash log:

`Caused by: java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_1867.method_8112()'                               at me.steven.indrev.recipes.PatchouliBookRecipe$Companion$Serializer.read(PatchouliBookRecipe.java:26) ~[indrev-0.3.0-BETA.jar:?]                                                                                                               at me.steven.indrev.recipes.PatchouliBookRecipe$Companion$Serializer.read(PatchouliBookRecipe.java:21) ~[indrev-0.3.0-BETA.jar:?]                                                                                                               at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:123) ~[?:?]
        at net.minecraft.recipe.RecipeManager.apply(RecipeManager:54) ~[?:?]
        at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
        at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]                                                                                                               at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
        at net.minecraft.resource.ResourceReloader.method_18367(ResourceReloader:70) ~[?:?]                                     at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]                        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]`

I noticed this with another mod implementing Patchouli books as well, so it could be a problem there.

**Comment by GabrielOlvH** [comment]
Oh, that's my bad, I already know the issue and it's a quick fix. I will reply here again as soon as the fixed version is available on curseforge. Sorry about that

**Comment by GabrielOlvH** [comment]
Fixed version is now available [here](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/2997110). I'm very sorry about this problem. Hope you enjoy the mod!
